#print("Hello World!")
#print("Hello Again")
#print("I like typing this.")
#print("This is fun.")
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
#print('I like python.')
#print('My name is Travis.')
print("What are you doing?")
print("My favorite football team is Manchester United.")
